# Add system packages for Python dependencies that require compilation
[phases.setup]
nixPkgs = [
  "python39",
  "gcc",
  "gxx", 
  "pkg-config",
  "cmake",
  "zlib",
  "libffi",
  "openssl",
  "freetype",
  "libjpeg",
  "libpng",
  "openblas"
]

# Let Railway handle the default install process
# This ensures pip and venv are properly set up 