# Add essential system packages for Python dependencies
[phases.setup]
nixPkgs = [
  "python39",
  "gcc",
  "pkg-config",
  "cmake",
  "zlib",
  "libffi",
  "openssl"
]

# Let Railway handle the default install process
# This ensures pip and venv are properly set up 