[phases.setup]
nixPkgs = ["python39", "gcc", "pkg-config"]

[phases.install]
cmds = ["pip install -r requirements.txt"]

[phases.build]
cmds = ["echo 'Build phase complete'"]

[start]
cmd = "python api.py" 