# Tells Nixpacks to use the 'backend' directory
watch = ["./backend"]

[phases.setup]
nixPkgs = ["python39", "gcc", "pkg-config"]
# The paths are now relative to the root, so we point to backend/requirements.txt
install_cmd = "pip install -r backend/requirements.txt"

[phases.build]
cmds = ["echo 'Build phase complete'"]

[start]
# The start command is also run from the root
cmd = "python backend/api.py" 