# This file tells Railway that the service is located in the 'backend' directory.
[build]
builder = "NIXPACKS"
rootDir = "/backend"

[deploy]
# The start command will be taken from the Procfile.
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10 