[build]
builder = "NIXPACKS"

[deploy]
startCommand = "python api.py"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[env]
PYTHONPATH = "/app"
PORT = "8000"

[variables]
PYTHON_VERSION = "3.9" 